/**
 * The CAD reference contract (issue #15 / ADR-012): the exact-package gate is
 * a project-owned `selection.expect.packages` lock where 0 is a valid,
 * reviewed value; `cad.enabled` is a capability flag that must be respected
 * rather than silently skipped; and every containment/size/VRML safety check
 * upstream had keeps working, parameterised instead of hard-coded.
 */

import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { mkdir, mkdtemp, readFile, rm, symlink, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { after, before, describe, it } from "node:test";

import type { Mesh, MeshPhongMaterial } from "three";
import { VRMLLoader } from "three/addons/loaders/VRMLLoader.js";

import { ComponentDocsError, type ErrorCode } from "../../src/core/errors.ts";
import type { InstanceSelection } from "../../src/core/publication.ts";
import {
  indexEvidence,
  type Inventory,
  type InventoryLine,
  type ProviderBundle,
  type ProviderPinMap,
  type ProviderRecord,
  type ProviderRoute,
} from "../../src/provider/v1/evidence.ts";
import {
  REFERENCE_LIMITS,
  UPSTREAM_MODEL_PREFIX,
  assertReferenceSize,
  assertSafePreviewAssetName,
  assertSameBasenamePair,
  readCircuitReferenceContract,
  validateVrml,
  type CircuitReferenceRoots,
} from "../../src/provider/v1/references.ts";

const VRML_HEADER = "#VRML V2.0 utf8\n";
const TRIANGLE = "geometry IndexedFaceSet { coord Coordinate { point [ 0 0 0, 1 0 0, 0 1 0 ] } coordIndex [ 0 1 2 -1 ] }";
const MATERIAL_USE_WRL =
  `${VRML_HEADER}Shape { appearance Appearance { material DEF PIN-01 Material { diffuseColor 1 0 0 } } ${TRIANGLE} }\n` +
  `Shape { appearance Appearance { material USE PIN-01 } ${TRIANGLE} }\n`;
const APPEARANCE_USE_WRL =
  `${VRML_HEADER}Shape { appearance DEF LOOK Appearance { material Material { diffuseColor 1 0 0 } } ${TRIANGLE} }\n` +
  `Shape { appearance USE LOOK ${TRIANGLE} }\n`;
// kicad-packages3D 8.0.9, recorded in examples/minimal/footprints/vendor/kicad-soic8/README.md.
const KICAD_SOIC8_WRL = new URL(
  "../../../../examples/minimal/footprints/vendor/kicad-soic8/SOIC-8_3.9x4.9mm_P1.27mm.wrl",
  import.meta.url,
);
const KICAD_SOIC8_WRL_SHA256 = "2b84645ac35f878381da69ebf467feab9e5f054922c809c1b28a1586dd4e462d";

// --- ported upstream unit tests (zudo-led-lamp tests/references.test.ts:100-136) ---
// Pure functions, unaffected by the options refactor: same inputs, same codes.

describe("preview assets fail closed", () => {
  const rejects = (fn: () => void, code: ErrorCode) =>
    assert.throws(fn, (error: unknown) => error instanceof ComponentDocsError && error.code === code);

  it("rejects traversal, absolute and external-looking asset names", () => {
    for (const path of ["../part.wrl", "/tmp/part.wrl", "models/part.wrl", "C:\\part.wrl", "https:part.wrl"]) {
      rejects(() => assertSafePreviewAssetName(path, "rec-hostile"), "PATH_CONTAINMENT");
    }
  });

  it("rejects resource-loading, executable and loader-unsupported VRML nodes", () => {
    for (const payload of [
      '#VRML V2.0 utf8\nInline { url "https://evil.invalid/model.wrl" }',
      '#VRML V2.0 utf8\nScript { url "javascript:alert(1)" }',
      '#VRML V2.0 utf8\nImageTexture { url "data:image/png;base64,AA" }',
      "#VRML V2.0 utf8\nTransform { children [] }",
      '#VRML V2.0 utf8\nShape { url "relative-model.wrl" }',
      "#VRML V2.0 utf8\nROUTE A.out TO B.in",
    ]) rejects(() => validateVrml(payload, "rec-hostile", "hostile.wrl"), "PUBLICATION_POLICY");
    rejects(
      () => validateVrml('#VRML V2.0 utf8\nShape { name "../../private/model.wrl" }', "rec-hostile", "hostile.wrl"),
      "PATH_CONTAINMENT",
    );
  });

  it("allows harmless URLs in generator comments but not live nodes", () => {
    assert.doesNotThrow(() =>
      validateVrml("#VRML V2.0 utf8\n# generated by https://example.invalid\nShape { }", "rec-safe", "safe.wrl"),
    );
  });

  it("accepts USE of a DEF'd Material or Appearance", () => {
    for (const payload of [MATERIAL_USE_WRL, APPEARANCE_USE_WRL]) {
      assert.doesNotThrow(() => validateVrml(payload, "rec-safe", "safe.wrl"));
    }
  });

  it("rejects USE of geometry, undefined names and anything but a material", () => {
    for (const payload of [
      // geometry reuse
      `${VRML_HEADER}Shape { geometry DEF G IndexedFaceSet { coord Coordinate { point [ 0 0 0 ] } } }\nShape { geometry USE G }`,
      // geometry DEF smuggled into a material slot
      `${VRML_HEADER}Shape { geometry DEF G IndexedFaceSet { } }\nShape { appearance Appearance { material USE G } }`,
      // coordinate reuse
      `${VRML_HEADER}Shape { geometry IndexedFaceSet { coord DEF C Coordinate { point [ 0 0 0 ] } } }\nShape { geometry IndexedFaceSet { coord USE C } }`,
      // whole-Shape reuse
      `${VRML_HEADER}DEF S Shape { }\nUSE S`,
      // undefined name
      `${VRML_HEADER}Shape { appearance Appearance { material USE MISSING } }`,
      // USE before its DEF
      `${VRML_HEADER}Shape { appearance Appearance { material USE M } }\nShape { appearance Appearance { material DEF M Material { } } }`,
      // a later DEF of the same name (the loader's last-DEF-wins) is not a Material
      `${VRML_HEADER}Shape { appearance Appearance { material DEF M Material { } } }\nShape { geometry DEF M IndexedFaceSet { } }\nShape { appearance Appearance { material USE M } }`,
      // Material DEF reused in the appearance slot
      `${VRML_HEADER}Shape { appearance Appearance { material DEF M Material { } } }\nShape { appearance USE M }`,
      // non-canonical keyword casing
      `${VRML_HEADER}Shape { appearance Appearance { material DEF M Material { } } }\nShape { appearance Appearance { material use M } }`,
    ]) rejects(() => validateVrml(payload, "rec-hostile", "hostile.wrl"), "PUBLICATION_POLICY");
  });

  it("renders material USE through the viewer's VRMLLoader with the DEF'd material", () => {
    const meshes: Mesh[] = [];
    new VRMLLoader().parse(MATERIAL_USE_WRL, "").traverse((object) => {
      if ((object as Mesh).isMesh) meshes.push(object as Mesh);
    });
    assert.equal(meshes.length, 2);
    for (const mesh of meshes) assert.equal((mesh.material as MeshPhongMaterial).color.getHexString(), "ff0000");
  });

  it("publishes the unmodified official KiCad StepUp WRL, which reuses materials", async () => {
    const vendored = await readFile(KICAD_SOIC8_WRL);
    assert.equal(createHash("sha256").update(vendored).digest("hex"), KICAD_SOIC8_WRL_SHA256);
    const contents = vendored.toString("utf8");
    assert.match(contents, /material USE /u);
    assert.doesNotThrow(() => validateVrml(contents, "rec-kicad", "SOIC-8_3.9x4.9mm_P1.27mm.wrl"));
  });

  it("rejects missing/mismatched format pairs and all size-cap violations", () => {
    rejects(() => assertSameBasenamePair("part.wrl", "other.step", "rec-hostile"), "ADAPTER_CONTRACT");
    rejects(() => assertSameBasenamePair("part.wrl", "part.stp", "rec-hostile"), "ADAPTER_CONTRACT");
    rejects(() => assertReferenceSize("footprint", REFERENCE_LIMITS.footprintBytes + 1, "rec-hostile"), "PUBLICATION_POLICY");
    rejects(() => assertReferenceSize("model", REFERENCE_LIMITS.modelBytes + 1, "rec-hostile"), "PUBLICATION_POLICY");
    rejects(() => assertReferenceSize("aggregate", REFERENCE_LIMITS.aggregateModelBytes + 1, "rec-hostile"), "PUBLICATION_POLICY");
  });

  it("accepts an overridden limit that the upstream default would have refused", () => {
    const overridden = { footprintBytes: 1, modelBytes: REFERENCE_LIMITS.modelBytes, aggregateModelBytes: REFERENCE_LIMITS.aggregateModelBytes };
    assert.doesNotThrow(() => assertReferenceSize("footprint", 1, "rec-fixture", overridden));
    rejects(() => assertReferenceSize("footprint", 2, "rec-fixture", overridden), "PUBLICATION_POLICY");
  });
});

// --- the reference contract against a scratch project on disk --------------

const SKILL = "cad-fixture";
const MODEL_PREFIX = "${KIPRJMOD}/cad-fixture.3dshapes/";
const WRL_TEXT = "#VRML V2.0 utf8\nShape {\n  geometry IndexedFaceSet {\n    coord Coordinate { point [ 0 0 0 ] }\n  }\n}\n";
const STEP_TEXT = "ISO-10303-21;\nEND-ISO-10303-21;\n";

let scratch = "";

before(async () => {
  scratch = await mkdtemp(join(tmpdir(), "circuit-doc-references-"));
});

after(async () => {
  await rm(scratch, { recursive: true, force: true });
});

function pcbLine(id: string): InventoryLine {
  return {
    line_id: id,
    mpn: `MPN-${id}`,
    manufacturer: "Fixture Mfr",
    lcsc: "C500001",
    package: "PKG-A",
    dnp: false,
    mounting: "pcb",
    owner_skill: SKILL,
    identity_state: "VERIFIED",
    source_state: "PRIMARY",
    function: "fixture part",
    placements: [{ board: "L", refdes: "U1" }],
  };
}

function externalLine(id: string): InventoryLine {
  return {
    line_id: id,
    mpn: `EXT-${id}`,
    manufacturer: "Fixture Mfr",
    lcsc: "",
    package: "EXT",
    dnp: false,
    mounting: "external",
    owner_skill: SKILL,
    identity_state: "VERIFIED",
    source_state: "PRIMARY",
    function: "external fixture part",
    placements: [],
  };
}

function record(id: string, lineId: string): ProviderRecord {
  return {
    record_id: id,
    line_id: lineId,
    kind: "standalone",
    parent_record_id: null,
    source_ids: [],
    fact_ids: [],
    interaction_ids: [],
    open_domains: [],
  };
}

function route(id: string, recordId: string): ProviderRoute {
  return { route_id: id, record_id: recordId, aliases: { mpn: [], lcsc: [], manufacturer: [], function: [] } };
}

function pinMap(id: string, recordId: string, footprint: string): ProviderPinMap {
  return { pin_map_id: id, record_id: recordId, symbol: footprint, footprint, pins: [] };
}

function bundleOf(records: ProviderRecord[], routes: ProviderRoute[], pinMaps: ProviderPinMap[]): ProviderBundle {
  return { skill: SKILL, records, sources: [], facts: [], coverage: [], routes, interactions: [], pinMaps };
}

function inventoryOf(lines: InventoryLine[]): Inventory {
  return {
    schema_version: 1,
    assertions: { orderable_lines: lines.length, fitted_lines: lines.length, dnp_or_hand_fit_lines: 0 },
    lines,
  };
}

/** A record/route/pinMap triple for a PCB-mounted part, plus its inventory line. */
function pcbFixture(recordId: string, lineId: string, footprint: string) {
  return {
    line: pcbLine(lineId),
    record: record(recordId, lineId),
    route: route(`route-${recordId}`, recordId),
    pinMap: pinMap(`pm-${recordId}`, recordId, footprint),
  };
}

/** A record/route/pinMap triple for an external (non-PCB) part. */
function externalFixture(recordId: string, lineId: string) {
  return {
    line: externalLine(lineId),
    record: record(recordId, lineId),
    route: route(`route-${recordId}`, recordId),
    pinMap: pinMap(`pm-${recordId}`, recordId, ""),
  };
}

/** Not asserted by `readCircuitReferenceContract` itself — only by `PublicationPolicy.assertSelectionFresh`, which this file never calls. */
function selectionFor(recordIds: readonly string[], packages: number | undefined): InstanceSelection {
  return {
    recordIds: [...recordIds],
    sourceIds: [],
    linkableSourceIds: [],
    documentSelections: [],
    expect: { records: 0, sources: 0, integrationRules: 0, ...(packages === undefined ? {} : { packages }) },
  };
}

function footprintText(name: string, locator: string): string {
  return [
    `(footprint "${name}"`,
    `  (model "${locator}"`,
    "    (offset (xyz 0 0 0))",
    "    (scale (xyz 1 1 1))",
    "    (rotate (xyz 0 0 90))",
    "  )",
    ")",
    "",
  ].join("\n");
}

async function makeRoots(caseName: string, createCadDirs = true): Promise<CircuitReferenceRoots> {
  const projectRoot = join(scratch, caseName);
  const footprintLibraryRoot = join(projectRoot, "footprints", "pretty");
  const modelRoot = join(projectRoot, "footprints", "3dshapes");
  await mkdir(projectRoot, { recursive: true });
  if (createCadDirs) {
    await mkdir(footprintLibraryRoot, { recursive: true });
    await mkdir(modelRoot, { recursive: true });
  }
  return { projectRoot, footprintLibraryRoot, modelRoot };
}

async function writeGoodPackage(roots: CircuitReferenceRoots, name: string): Promise<void> {
  await writeFile(join(roots.footprintLibraryRoot, `${name}.kicad_mod`), footprintText(name, `${MODEL_PREFIX}${name}.wrl`));
  await writeFile(join(roots.modelRoot, `${name}.wrl`), WRL_TEXT);
  await writeFile(join(roots.modelRoot, `${name}.step`), STEP_TEXT);
}

describe("readCircuitReferenceContract", () => {
  it("resolves one package from a STEP+WRL pair for a PCB-mounted record", async () => {
    const roots = await makeRoots("happy-path");
    await writeGoodPackage(roots, "PKG-A");
    const { line, record: rec, route: rt, pinMap: pm } = pcbFixture("rec-pcb", "line-pcb", "PKG-A");
    const index = indexEvidence(inventoryOf([line]), [bundleOf([rec], [rt], [pm])], []);

    const contract = await readCircuitReferenceContract(
      index,
      selectionFor(["rec-pcb"], 1),
      roots,
      { modelLocatorPrefix: MODEL_PREFIX },
    );

    assert.equal(contract.packages.length, 1);
    assert.equal(contract.packages[0]?.packageId, "PKG-A");
    assert.equal(contract.packages[0]?.footprintPath, "footprints/pretty/PKG-A.kicad_mod");
    assert.equal(contract.packages[0]?.modelPath, "footprints/3dshapes/PKG-A.wrl");
    assert.deepEqual(contract.packages[0]?.rotation, { x: 0, y: 0, z: 90 });
    assert.equal(contract.packageByRecordId.get("rec-pcb")?.packageId, "PKG-A");
  });

  it("reads the multi-line model transforms KiCad 9 writes", async () => {
    const roots = await makeRoots("kicad9-transforms");
    await writeGoodPackage(roots, "PKG-A");
    await writeFile(
      join(roots.footprintLibraryRoot, "PKG-A.kicad_mod"),
      [
        '(footprint "PKG-A"',
        `\t(model "${MODEL_PREFIX}PKG-A.wrl"`,
        "\t\t(offset\n\t\t\t(xyz 0 0 0.1)\n\t\t)",
        "\t\t(scale\n\t\t\t(xyz 1 1 1)\n\t\t)",
        "\t\t(rotate\n\t\t\t(xyz 0 0 -90)\n\t\t)",
        "\t)",
        ")",
        "",
      ].join("\n"),
    );
    const { line, record: rec, route: rt, pinMap: pm } = pcbFixture("rec-pcb", "line-pcb", "PKG-A");
    const index = indexEvidence(inventoryOf([line]), [bundleOf([rec], [rt], [pm])], []);

    const contract = await readCircuitReferenceContract(index, selectionFor(["rec-pcb"], 1), roots, {
      modelLocatorPrefix: MODEL_PREFIX,
    });

    assert.deepEqual(contract.packages[0]?.offset, { x: 0, y: 0, z: 0.1 });
    assert.deepEqual(contract.packages[0]?.scale, { x: 1, y: 1, z: 1 });
    assert.deepEqual(contract.packages[0]?.rotation, { x: 0, y: 0, z: -90 });
  });

  it("CAD-05: 0 selected packages passes with no CAD directories at all", async () => {
    const roots = await makeRoots("zero-state", false);
    const index = indexEvidence(inventoryOf([]), [bundleOf([], [], [])], []);

    const contract = await readCircuitReferenceContract(index, selectionFor([], 0), roots, {});

    assert.deepEqual(contract.packages, []);
  });

  it("an external record needs no footprint or model, whether or not CAD is enabled", async () => {
    const roots = await makeRoots("external-record", false);
    const { line, record: rec, route: rt, pinMap: pm } = externalFixture("rec-ext", "line-ext");
    const index = indexEvidence(inventoryOf([line]), [bundleOf([rec], [rt], [pm])], []);

    for (const enabled of [true, false]) {
      const contract = await readCircuitReferenceContract(index, selectionFor(["rec-ext"], 0), roots, { enabled });
      assert.deepEqual(contract.packages, []);
    }
  });

  it("CAD disabled refuses a selected PCB-mounted record instead of silently skipping it", async () => {
    const roots = await makeRoots("disabled-pcb", false);
    const { line, record: rec, route: rt, pinMap: pm } = pcbFixture("rec-pcb", "line-pcb", "PKG-A");
    const index = indexEvidence(inventoryOf([line]), [bundleOf([rec], [rt], [pm])], []);

    await rejectsWith(
      readCircuitReferenceContract(index, selectionFor(["rec-pcb"], undefined), roots, { enabled: false }),
      "ADAPTER_CONTRACT",
      /CAD capability disabled but record rec-pcb requires a footprint\/model reference/u,
    );
  });

  it("CAD disabled with a non-zero package lock still refuses the PCB-mounted record", async () => {
    const roots = await makeRoots("disabled-pcb-locked", false);
    const { line, record: rec, route: rt, pinMap: pm } = pcbFixture("rec-pcb", "line-pcb", "PKG-A");
    const index = indexEvidence(inventoryOf([line]), [bundleOf([rec], [rt], [pm])], []);

    await rejectsWith(
      readCircuitReferenceContract(index, selectionFor(["rec-pcb"], 1), roots, { enabled: false }),
      "ADAPTER_CONTRACT",
      /CAD capability disabled but record rec-pcb requires a footprint\/model reference/u,
    );
  });

  it("CAD disabled with a declared-zero package lock lists the PCB record as unpublished, not external (ADR-012)", async () => {
    const roots = await makeRoots("disabled-pcb-declared-zero", false);
    const { line, record: rec, route: rt, pinMap: pm } = pcbFixture("rec-pcb", "line-pcb", "PKG-A");
    const index = indexEvidence(inventoryOf([line]), [bundleOf([rec], [rt], [pm])], []);

    const contract = await readCircuitReferenceContract(index, selectionFor(["rec-pcb"], 0), roots, { enabled: false });

    assert.deepEqual(contract.packages, []);
    assert.equal(contract.packageByRecordId.has("rec-pcb"), false);
    assert.deepEqual([...contract.unpublishedPackageRecordIds], ["rec-pcb"]);
  });

  it("an external record is never listed as unpublished, even with CAD disabled", async () => {
    const roots = await makeRoots("enabled-no-unpublished", false);
    const { line, record: rec, route: rt, pinMap: pm } = externalFixture("rec-ext", "line-ext");
    const index = indexEvidence(inventoryOf([line]), [bundleOf([rec], [rt], [pm])], []);

    const contract = await readCircuitReferenceContract(index, selectionFor(["rec-ext"], 0), roots, { enabled: false });

    assert.deepEqual([...contract.unpublishedPackageRecordIds], []);
  });

  it("a lock mismatch names the expected and actual package counts", async () => {
    const roots = await makeRoots("lock-mismatch");
    await writeGoodPackage(roots, "PKG-A");
    const { line, record: rec, route: rt, pinMap: pm } = pcbFixture("rec-pcb", "line-pcb", "PKG-A");
    const index = indexEvidence(inventoryOf([line]), [bundleOf([rec], [rt], [pm])], []);

    await assert.rejects(
      readCircuitReferenceContract(index, selectionFor(["rec-pcb"], 2), roots, { modelLocatorPrefix: MODEL_PREFIX }),
      (error: unknown) => {
        assert.ok(error instanceof ComponentDocsError);
        assert.equal(error.code, "ADAPTER_CONTRACT");
        assert.equal(error.detail.expected, 2);
        assert.equal(error.detail.actual, 1);
        return true;
      },
    );
  });

  it("a missing selected model file fails naming the path and the record", async () => {
    const roots = await makeRoots("missing-model");
    await writeFile(join(roots.footprintLibraryRoot, "PKG-A.kicad_mod"), footprintText("PKG-A", `${MODEL_PREFIX}PKG-A.wrl`));
    // Deliberately never write PKG-A.wrl.
    const { line, record: rec, route: rt, pinMap: pm } = pcbFixture("rec-pcb", "line-pcb", "PKG-A");
    const index = indexEvidence(inventoryOf([line]), [bundleOf([rec], [rt], [pm])], []);

    await assert.rejects(
      readCircuitReferenceContract(index, selectionFor(["rec-pcb"], 1), roots, { modelLocatorPrefix: MODEL_PREFIX }),
      (error: unknown) => {
        assert.ok(error instanceof ComponentDocsError);
        assert.equal(error.code, "ADAPTER_CONTRACT");
        assert.equal(error.detail.recordId, "rec-pcb");
        assert.ok(String(error.detail.path).includes("PKG-A.wrl"), String(error.detail.path));
        return true;
      },
    );
  });

  it("a model locator escaping the root fails PATH_CONTAINMENT", async () => {
    const roots = await makeRoots("escaping-locator");
    await writeFile(
      join(roots.footprintLibraryRoot, "PKG-A.kicad_mod"),
      footprintText("PKG-A", `${MODEL_PREFIX}../../../etc/evil.wrl`),
    );
    const { line, record: rec, route: rt, pinMap: pm } = pcbFixture("rec-pcb", "line-pcb", "PKG-A");
    const index = indexEvidence(inventoryOf([line]), [bundleOf([rec], [rt], [pm])], []);

    await rejectsWith(
      readCircuitReferenceContract(index, selectionFor(["rec-pcb"], 1), roots, { modelLocatorPrefix: MODEL_PREFIX }),
      "PATH_CONTAINMENT",
      /unsafe WRL name/u,
    );
  });

  it("a symlinked model file fails PATH_CONTAINMENT", async () => {
    const roots = await makeRoots("symlinked-model");
    await writeFile(join(roots.footprintLibraryRoot, "PKG-A.kicad_mod"), footprintText("PKG-A", `${MODEL_PREFIX}PKG-A.wrl`));
    await writeFile(join(roots.modelRoot, "PKG-A.step"), STEP_TEXT);
    // The symlink target stays inside modelRoot, so only the symlink check (not
    // the escape check) is exercised here.
    const real = join(roots.modelRoot, "real-target.wrl");
    await writeFile(real, WRL_TEXT);
    await symlink(real, join(roots.modelRoot, "PKG-A.wrl"));
    const { line, record: rec, route: rt, pinMap: pm } = pcbFixture("rec-pcb", "line-pcb", "PKG-A");
    const index = indexEvidence(inventoryOf([line]), [bundleOf([rec], [rt], [pm])], []);

    await rejectsWith(
      readCircuitReferenceContract(index, selectionFor(["rec-pcb"], 1), roots, { modelLocatorPrefix: MODEL_PREFIX }),
      "PATH_CONTAINMENT",
      /regular non-symlink file/u,
    );
  });

  it("defaults the model locator prefix to the upstream one, not the project's own", async () => {
    const roots = await makeRoots("default-prefix");
    await writeGoodPackage(roots, "PKG-A");
    const { line, record: rec, route: rt, pinMap: pm } = pcbFixture("rec-pcb", "line-pcb", "PKG-A");
    const index = indexEvidence(inventoryOf([line]), [bundleOf([rec], [rt], [pm])], []);

    assert.notEqual(MODEL_PREFIX, UPSTREAM_MODEL_PREFIX);
    await rejectsWith(
      readCircuitReferenceContract(index, selectionFor(["rec-pcb"], 1), roots, {}),
      "PATH_CONTAINMENT",
      /not a safe local WRL/u,
    );
  });

  it("computes footprintPath/modelPath relative to an overridden footprintPathBase", async () => {
    const roots = await makeRoots("path-base");
    await writeGoodPackage(roots, "PKG-A");
    const { line, record: rec, route: rt, pinMap: pm } = pcbFixture("rec-pcb", "line-pcb", "PKG-A");
    const index = indexEvidence(inventoryOf([line]), [bundleOf([rec], [rt], [pm])], []);

    const contract = await readCircuitReferenceContract(
      index,
      selectionFor(["rec-pcb"], 1),
      roots,
      { modelLocatorPrefix: MODEL_PREFIX, footprintPathBase: join(roots.projectRoot, "footprints") },
    );

    assert.equal(contract.packages[0]?.footprintPath, "pretty/PKG-A.kicad_mod");
    assert.equal(contract.packages[0]?.modelPath, "3dshapes/PKG-A.wrl");
  });

  it("overridden size limits gate the same checks as the upstream defaults", async () => {
    const roots = await makeRoots("tight-limits");
    await writeGoodPackage(roots, "PKG-A");
    const { line, record: rec, route: rt, pinMap: pm } = pcbFixture("rec-pcb", "line-pcb", "PKG-A");
    const index = indexEvidence(inventoryOf([line]), [bundleOf([rec], [rt], [pm])], []);

    await rejectsWith(
      readCircuitReferenceContract(index, selectionFor(["rec-pcb"], 1), roots, {
        modelLocatorPrefix: MODEL_PREFIX,
        limits: { footprintBytes: 1 },
      }),
      "PUBLICATION_POLICY",
      /exceeds preview size limit/u,
    );
  });
});

// --- helpers -----------------------------------------------------------------

async function rejectsWith(run: Promise<unknown>, code: ErrorCode, message: RegExp): Promise<void> {
  await assert.rejects(run, (error: unknown) => {
    assert.ok(error instanceof ComponentDocsError, String(error));
    assert.equal(error.code, code, error.message);
    assert.match(error.message, message);
    return true;
  });
}
