import type { CircuitConfig } from "../../src/config/define.ts";

/** The generated-project default (`examples/empty` / `templates/default`). */
export const DEFAULT_PROJECT_CONFIG = {
  configVersion: 1,
  project: { name: "my-circuit", title: "My Circuit" },
  docs: {
    root: "doc",
    generatedContent: "doc/src/content/docs/components",
    preflight: "circuit/generated/preflight.json",
    publicRoot: "doc/public",
    dist: "doc/dist",
    agentResources: true,
  },
  evidence: {
    contractVersion: 1,
    bundlesRoot: ".claude/skills",
    ownerPrefix: "component-",
    auditSkill: "component-spec-audit",
    integrationSkill: "circuit-spec-integration",
    inventory: ".claude/skills/component-spec-audit/references/inventory.json",
    integrationRules: ".claude/skills/circuit-spec-integration/references/rules.json",
    directRouting: ".claude/skills/component-spec-audit/references/direct-routing.json",
    vendorQualifiers: ".claude/skills/component-spec-audit/references/external-vendor-qualifiers.json",
    sourceCache: ".circuit-cache/sources",
  },
  inventoryProvider: { kind: "manual" },
  publication: {
    selection: "circuit/publication/selection.json",
    assets: "circuit/publication/assets.json",
  },
  cad: { enabled: false, libraryName: "my-circuit" },
  validation: {},
} satisfies CircuitConfig;

/** LED-style: data under `upstream/`, generator provider, CAD enabled. */
export const LED_STYLE_CONFIG = {
  configVersion: 1,
  root: "upstream",
  project: { name: "zudo-led-lamp", title: "zudo-led-lamp" },
  docs: {
    root: "upstream/doc",
    generatedContent: "upstream/doc/src/content/docs/components",
    preflight: "upstream/doc/component-docs/generated/preflight.json",
    publicRoot: "upstream/doc/public",
    dist: "upstream/doc/dist",
    agentResources: true,
    generatedMarker: "# GENERATED by doc/component-docs — do not edit; run `pnpm generate:components`",
    integrationGloss: "integration-gloss.json",
  },
  evidence: {
    contractVersion: 1,
    bundlesRoot: "upstream/.claude/skills",
    ownerPrefix: "component-",
    auditSkill: "component-spec-audit",
    integrationSkill: "circuit-spec-integration",
    inventory: "upstream/.claude/skills/component-spec-audit/references/inventory.json",
    integrationRules: "upstream/.claude/skills/circuit-spec-integration/references/rules.json",
    directRouting: "upstream/.claude/skills/component-spec-audit/references/direct-routing.json",
    vendorQualifiers: "upstream/.claude/skills/component-spec-audit/references/external-vendor-qualifiers.json",
    forwardTests: null,
    sourceCache: ".circuit-cache/sources",
  },
  inventoryProvider: {
    kind: "led-generator-v1",
    specs: [{ path: "upstream/scripts/schgen/board_p_spec.py" }, { path: "upstream/scripts/schgen/board_l_spec.py" }],
  },
  publication: {
    selection: "selection.json",
    assets: "assets.json",
  },
  cad: {
    enabled: true,
    libraryName: "zudo-led-lamp",
    symbolLibraries: ["upstream/symbols/zudo-led-lamp.kicad_sym"],
    footprintMasterRoot: "upstream/footprints/kicad",
    footprintLibraryRoot: "upstream/footprints/kicad/zudo-led-lamp.pretty",
    modelRoot: "upstream/footprints/kicad/zudo-led-lamp.3dshapes",
    modelLocatorPrefix: "${KIPRJMOD}/../../footprints/kicad/zudo-led-lamp.3dshapes/",
    previewRenderer: {
      image: "kicad/kicad@sha256:e638b79b0321f29395a5b783e94bb9f3c73303e8da15da27b8f5cb4b67a37729",
      version: "9.0.9",
      platform: "linux/amd64",
      layers: ["F.Cu", "F.Silkscreen", "F.Fabrication", "F.Courtyard"],
      theme: "KiCad Default",
      options: ["--black-and-white"],
    },
  },
  validation: { pythonMinVersion: "3.10", policy: "policy.json" },
  scan: { minimumOwnedCanaries: 100, expectedWithheld: 6, positiveControlRecord: "al8860mp-13" },
  browserSmoke: {
    representatives: [
      { kind: "IC", path: "/docs/components/records/al8860mp-13/", slug: "al8860mp-13", identity: "AL8860MP-13" },
    ],
  },
} satisfies CircuitConfig;

/** A structural deep clone typed loosely, so tests can break it. */
export function mutable(value: unknown): Record<string, any> {
  return structuredClone(value) as Record<string, any>;
}
