import { mkdir, writeFile, readFile, rm } from "node:fs/promises";
const E = "$HOME/repos/circuits/zudo-led-lamp/doc/component-docs";
const { emit } = await import(`${E}/core/emit.ts`);
const root = new URL("./gap-root/", import.meta.url).pathname;
await rm(root, { recursive: true, force: true });
await mkdir(root, { recursive: true });
await writeFile(root + "index.mdx", "---\ntitle: hand\n---\nHAND-AUTHORED\n");
await writeFile(root + "stray.mdx", "---\ntitle: stray\n---\nstray\n");
const page = { relativePath: "index.mdx", contents: "---\n# GENERATED by doc/component-docs — do not edit; run `pnpm generate:components`\ntitle: \"x\"\n---\n\nnew\n", anchors: [], links: [] };
try { await emit({ root, pages: [page] }); } catch (e) { console.log("threw:", e.message); }
console.log("index.mdx now:", JSON.stringify((await readFile(root + "index.mdx", "utf8")).slice(0, 60)));
