/**
 * Synthetic preflight reports, generated record pages and built pages for the
 * derived-representatives tests (#47). Not a `*.test.ts` file, so `node --test`
 * does not pick it up as a suite.
 */

import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";

import { createComponentReferencesDescriptor, encodeComponentReferencesDescriptor } from "../../src/core/reference-descriptor.ts";

const PACKAGE = "SOIC-8";

async function write(path: string, text: string): Promise<void> {
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, text, "utf8");
}

export async function writePreflight(path: string, slugs: readonly string[]): Promise<void> {
  await write(path, `${JSON.stringify({ records: { available: slugs.length, selected: slugs.length, slugs } }, null, 2)}\n`);
}

function referencesDescriptor(): string {
  return encodeComponentReferencesDescriptor(
    createComponentReferencesDescriptor({
      document: {
        label: "Datasheet PDF",
        title: "Datasheet",
        authority: "MANUFACTURER_PRIMARY",
        availability: "AVAILABLE",
        url: "https://example.com/datasheet.pdf",
      },
      footprintName: PACKAGE,
      model: {
        version: 1,
        packageId: PACKAGE,
        packageLabel: PACKAGE,
        modelUrl: `/assets/component-previews/models/${PACKAGE}.wrl`,
        offset: { x: 0, y: 0, z: 0 },
        rotation: { x: 0, y: 0, z: 0 },
        scale: { x: 1, y: 1, z: 1 },
      },
    }),
  );
}

export type RecordPageOptions = {
  readonly identity: string;
  /** `false` omits the ComponentReferences block (a record with no published CAD references). */
  readonly references?: boolean;
  /** Overrides the encoded descriptor, e.g. with an undecodable one. */
  readonly descriptor?: string;
};

/** `<generatedRoot>/records/<slug>/index.mdx`, shaped like `core/render/record.ts` output. */
export async function writeRecordPage(generatedRoot: string, slug: string, options: RecordPageOptions): Promise<void> {
  const references =
    options.references === false
      ? "No footprint or model is published for this record.\n"
      : `<ComponentReferences descriptor="${options.descriptor ?? referencesDescriptor()}" />\n`;
  await write(
    join(generatedRoot, "records", slug, "index.mdx"),
    [
      "---",
      "# GENERATED by @takazudo/zudo-circuit-doc — do not edit; run `zudo-circuit-doc generate`",
      `title: ${JSON.stringify(options.identity)}`,
      `description: ${JSON.stringify(`part — rec-${slug}`)}`,
      "sidebar_position: 1",
      "---",
      "",
      "## Documents and package",
      "",
      references,
      "## Facts",
      "",
      "<EvidenceFact>",
      "A fact.",
      "</EvidenceFact>",
      "",
      "## Sources",
      "",
    ].join("\n"),
  );
}

/** A built page for `slug` carrying the component-references marker, plus (by default) its footprint/model assets. */
export async function writeBuiltRecord(distRoot: string, slug: string, options: { readonly assets?: boolean } = {}): Promise<void> {
  await write(join(distRoot, "index.html"), "<html></html>");
  await write(join(distRoot, "docs/components/records", slug, "index.html"), '<section class="zcd-component-references"></section>');
  if (options.assets !== false) {
    await write(join(distRoot, `assets/component-previews/footprints/${PACKAGE}.svg`), "<svg/>");
    await write(join(distRoot, `assets/component-previews/models/${PACKAGE}.wrl`), "#VRML V2.0 utf8\n");
  }
}
