// Core library for the fixture site build harness (#23).
//
// Builds a standalone, out-of-workspace zudo-doc site from a fixture's pinned
// evidence corpus (currently only `led`), depending on the packaged
// `@takazudo/zudo-circuit-doc` runtime the same way a real generated project
// would — a packed tarball (`--mode pack`, the default) or the built package
// directory injected by pnpm (`--mode file-dir`) — never `link:` (a symlink
// back into this monorepo would resolve `preact`/`@takazudo/zudo-doc` from
// THIS repo's own node_modules instead of the fixture site's, duplicating
// both). See `scripts/build-fixture-site.mjs` for the CLI entry point and
// `fixtures/led/circuit/site-overlay.json` for the docs.* path rewrite this
// module applies.
//
// High-level flow for `fixture: "led"`:
//   1. copy `fixtures/led/upstream/**` verbatim into `<out>/upstream` (the
//      project data root; config keeps `root: "upstream"`) and
//      `fixtures/led/circuit/*.json` into `<out>/circuit/*.json`.
//   2. derive `<out>/circuit.config.ts` from `fixtures/led/circuit.config.ts`
//      by importing its resolved config object and overlaying
//      `circuit/site-overlay.json`'s `docs.*` rewrite (upstream/doc/... ->
//      doc/... — the fixture's own host layout, once step 3 grafts one on).
//   3. overlay `examples/empty/doc/`'s host files (route stub, chrome
//      bindings, global.css, check-links.js, favicons, tsconfig) into
//      `<out>/doc/`, then generate `<out>/package.json`, `<out>/doc/package.json`,
//      `<out>/pnpm-workspace.yaml` and `<out>/doc/zfb.config.ts` (siteName +
//      a headerNav trimmed to only the sections this fixture actually
//      authors — Components only — so `--strict-broken` has nothing to
//      complain about).
//   4. seed the (now rewritten) generated-content, preflight and public-asset
//      locations with the pinned LED goldens and committed previews, then
//      `git init` + one commit — so `models`/`generate` re-writing the exact
//      same bytes shows up as "zero drift" in `git status`, and zudo-doc's
//      docHistory feature has one quiet commit to read instead of none.
//   5. obtain the runtime package (pack the workspace package into a tarball,
//      or point `file:` at the built package directory), install with
//      `corepack pnpm install --config.strict-dep-builds=true`, and assert a
//      single `preact`/`@takazudo/zudo-doc` instance.
//   6. `pnpm run build` (models -> generate -> zfb build), assert zero drift
//      against the seeded goldens, then `pnpm run check:site` (check-built,
//      scan against the re-baselined `circuit/scan-policy.json`, and
//      `check-links.js --strict-anchors --strict-broken`).

import { execFileSync, spawnSync } from "node:child_process";
import {
  cpSync,
  existsSync,
  mkdirSync,
  mkdtempSync,
  readdirSync,
  readFileSync,
  realpathSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { createRequire } from "node:module";
import { tmpdir } from "node:os";
import path from "node:path";
import { pathToFileURL } from "node:url";

import { checkFixture } from "../sync-led-fixture.mjs";

export const REPO_ROOT = path.resolve(import.meta.dirname, "../..");
export const RUNTIME_PACKAGE_DIR = path.join(REPO_ROOT, "packages/circuit-doc");
export const RUNTIME_PACKAGE_NAME = "@takazudo/zudo-circuit-doc";

const HOST_EXAMPLE_DIR = path.join(REPO_ROOT, "examples/empty/doc");
// Regenerated by this harness, never copied verbatim from the host example.
const HOST_FILES_EXCLUDE = new Set(["package.json", "zfb.config.ts", "node_modules"]);

const LED_FIXTURE_DIR = path.join(REPO_ROOT, "fixtures/led");

const FIXTURES = {
  led: {
    key: "led",
    fixtureDir: LED_FIXTURE_DIR,
    configFile: path.join(LED_FIXTURE_DIR, "circuit.config.ts"),
    siteOverlayFile: path.join(LED_FIXTURE_DIR, "circuit/site-overlay.json"),
    projectName: "led-fixture-circuit",
    siteName: "LED Regression Fixture",
    // Relative to fixtureDir.
    goldenGeneratedContent: "upstream/doc/src/content/docs/components",
    goldenPreflightUpstream: "upstream/doc/component-docs/preflight.json",
    goldenPreflightExpected: "expected/doc/component-docs/preflight.json",
    goldenPublic: "upstream/doc/public",
  },
};

export function resolveFixture(name) {
  const def = FIXTURES[name];
  if (def === undefined) {
    throw new Error(
      `unknown --fixture "${name}" (known: ${Object.keys(FIXTURES).join(", ")}); ` +
        '"minimal" is reserved for #25/#31 and is not wired into this harness yet',
    );
  }
  return def;
}

// --- small fs/proc helpers --------------------------------------------------

function readJson(filePath) {
  return JSON.parse(readFileSync(filePath, "utf8"));
}

function writeJson(filePath, data) {
  mkdirSync(path.dirname(filePath), { recursive: true });
  writeFileSync(filePath, `${JSON.stringify(data, null, 2)}\n`);
}

function writeText(filePath, text) {
  mkdirSync(path.dirname(filePath), { recursive: true });
  writeFileSync(filePath, text);
}

function copyTree(src, dest, options = {}) {
  mkdirSync(dest, { recursive: true });
  cpSync(src, dest, { recursive: true, ...options });
}

function run(command, args, options) {
  const result = spawnSync(command, args, { encoding: "utf8", ...options });
  if (result.error) throw result.error;
  return { code: result.status ?? 1, stdout: result.stdout ?? "", stderr: result.stderr ?? "" };
}

function assertRunOk(label, result) {
  if (result.code !== 0) {
    throw new Error(`\`${label}\` failed (exit ${result.code}):\n${result.stdout}${result.stderr}`);
  }
}

function runPnpm(args, options) {
  return run("corepack", ["pnpm", ...args], options);
}

function gitFixtureStatus() {
  return execFileSync("git", ["status", "--porcelain", "--", "fixtures/led"], { cwd: REPO_ROOT, encoding: "utf8" });
}

// --- step 1: copy fixture data ----------------------------------------------

function copyLedData(def, outDir) {
  copyTree(path.join(def.fixtureDir, "upstream"), path.join(outDir, "upstream"));
  // zfb's `claudeResources` feature (wired by the doc/zfb.config.ts this
  // harness generates, same as examples/empty) scans a fixed location,
  // `../.claude` relative to `doc/` — the "project root .claude/skills/"
  // convention a real generated project follows. The LED fixture keeps its
  // evidence nested at `upstream/.claude/skills` instead (a fixture-only
  // convenience, unrelated to this harness), so without this extra copy the
  // generated pages' `/docs/claude-skills/<owner>/` links 404 and
  // check-links fails. `evidence.bundlesRoot` stays "upstream/.claude/skills"
  // (unchanged) — this is a second, disposable copy for zfb's doc mirror
  // only, never the validator/generator's evidence source of truth.
  copyTree(path.join(outDir, "upstream/.claude"), path.join(outDir, ".claude"));
  const circuitSrc = path.join(def.fixtureDir, "circuit");
  const circuitDest = path.join(outDir, "circuit");
  mkdirSync(circuitDest, { recursive: true });
  for (const entry of readdirSync(circuitSrc)) {
    // site-overlay.json is a build-tool-only input (this script reads it
    // directly); it is not part of the CircuitConfig contract and has no
    // reason to ship inside the generated fixture project.
    if (entry === "site-overlay.json") continue;
    cpSync(path.join(circuitSrc, entry), path.join(circuitDest, entry), { recursive: true });
  }
}

// --- step 2: derive circuit.config.ts ---------------------------------------

async function deriveConfig(def, outDir) {
  const mod = await import(pathToFileURL(def.configFile).href);
  const base = mod.default;
  const overlay = readJson(def.siteOverlayFile);
  // Shallow-merge every overlay section (currently `docs` and `publication`)
  // over the matching base section; `_comment` is documentation only.
  const merged = { ...base };
  for (const [key, value] of Object.entries(overlay)) {
    if (key.startsWith("_")) continue;
    merged[key] = { ...(base[key] ?? {}), ...value };
  }
  const source =
    "/**\n" +
    ` * LED FIXTURE SITE config — generated by scripts/build-fixture-site.mjs (#23)\n` +
    " * from fixtures/led/circuit.config.ts + fixtures/led/circuit/site-overlay.json.\n" +
    " * Do not edit by hand; edit those two files and rebuild the fixture site instead.\n" +
    " */\n" +
    'import type { CircuitConfig } from "@takazudo/zudo-circuit-doc/config";\n\n' +
    `export default ${JSON.stringify(merged, null, 2)} satisfies CircuitConfig;\n`;
  writeText(path.join(outDir, "circuit.config.ts"), source);
  return merged;
}

// --- step 3: host overlay + generated manifests -----------------------------

function copyHostFiles(outDir) {
  const docDir = path.join(outDir, "doc");
  mkdirSync(docDir, { recursive: true });
  cpSync(HOST_EXAMPLE_DIR, docDir, {
    recursive: true,
    filter: (src) => !HOST_FILES_EXCLUDE.has(path.basename(src)),
  });
}

function dependencySpecFor({ mode, tarballPath, builtPackageDir }) {
  if (tarballPath !== null) return { spec: `file:${tarballPath}`, injected: false };
  if (mode === "pack") return { spec: `file:${tarballPath}`, injected: false };
  if (mode === "file-dir") return { spec: `file:${builtPackageDir}`, injected: true };
  throw new Error(`unknown mode: ${mode}`);
}

function writeRootPackageJson(outDir, def, dependency) {
  const source = readJson(path.join(REPO_ROOT, "examples/empty/package.json"));
  const pkg = {
    ...source,
    name: def.projectName,
    devDependencies: { [RUNTIME_PACKAGE_NAME]: dependency.spec },
  };
  if (dependency.injected) {
    pkg.dependenciesMeta = { ...(pkg.dependenciesMeta ?? {}), [RUNTIME_PACKAGE_NAME]: { injected: true } };
  }
  writeJson(path.join(outDir, "package.json"), pkg);
}

function writeDocPackageJson(outDir, def, dependency) {
  const source = readJson(path.join(REPO_ROOT, "examples/empty/doc/package.json"));
  const pkg = {
    ...source,
    name: `${def.projectName}-doc`,
    dependencies: { ...source.dependencies, [RUNTIME_PACKAGE_NAME]: dependency.spec },
  };
  if (dependency.injected) {
    pkg.dependenciesMeta = { ...(pkg.dependenciesMeta ?? {}), [RUNTIME_PACKAGE_NAME]: { injected: true } };
  }
  writeJson(path.join(outDir, "doc/package.json"), pkg);
}

function writePnpmWorkspaceYaml(outDir) {
  // ADR-003 "Generated project contract": generated-project pnpm settings
  // live only here, and there are no `.npmrc` files. `minimumReleaseAge: 0`
  // disables pnpm 11's default 1-day supply-chain wait outright (this project
  // never resolves from the public registry with a real recency signal to
  // check anyway: its one first-party dependency is a local `file:` tarball,
  // which pnpm never subjects to the release-age check).
  writeText(
    path.join(outDir, "pnpm-workspace.yaml"),
    "packages:\n  - doc\nminimumReleaseAge: 0\nallowBuilds:\n  esbuild: true\n",
  );
}

/**
 * `examples/empty/doc/zfb.config.ts`, with `siteName` and `headerNav`
 * parameterized. `headerNav` is cut down to just the Components dropdown
 * (spec item 1.3): this fixture authors no project/architecture/research/
 * decisions/verification pages, and `--strict-broken` (run in step 6) fails
 * on a header entry pointing at a section that does not exist.
 */
function buildZfbConfigSource(siteName) {
  return `import { defineConfig } from "zfb/config";
import { zudoDoc } from "@takazudo/zudo-doc/config";

// Generated by scripts/build-fixture-site.mjs (#23) from
// examples/empty/doc/zfb.config.ts: same host conventions, but \`siteName\`
// and a \`headerNav\` trimmed to the sections this fixture actually authors
// (see that file's own header comment for the constraints that carry over
// unchanged — no \`circuit.config.ts\` import, no \`node:*\` imports).
const site = zudoDoc({
  siteName: ${JSON.stringify(siteName)},
  base: "/",
  defaultLocale: "en",
  themePacks: ["default"],
  llmsTxt: true,
  cjkFriendly: true,
  dynamicPageTransition: true,
  docHistory: true,
  docHistoryExclude: ["components", "components/**"],
  assetViewer: true,
  strictContentBridge: true,
  claudeResources: { claudeDir: "../.claude", scanRoot: ".." },
  defaultLocaleOnlyPrefixes: [
    "/docs/components/",
    "/docs/claude/",
    "/docs/claude-md/",
    "/docs/claude-skills/",
    "/docs/claude-agents/",
    "/docs/claude-commands/",
  ],
  chromeBindingsModule: "./src/chrome-bindings.tsx",
  headerNav: [
    {
      label: "Components",
      path: "/docs/components",
      categoryMatch: "components",
      children: [
        { label: "Catalog & Records", path: "/docs/components", categoryMatch: "components" },
        { label: "Raw agent resources", path: "/docs/claude", categoryMatch: "claude", versioned: false },
      ],
    },
  ],
  headerRightItems: [
    { type: "component", component: "theme-toggle" },
    { type: "component", component: "search" },
  ],
  footer: {
    links: [],
    copyright: "Built with zudo-circuit-doc on zudo-doc.",
  },
});

// Same source-level \`linkValidation\` removal as examples/empty (#68): it
// cannot see ids rendered by \`<EvidenceAnchor>\`, and the built-HTML
// \`check:links --strict-anchors --strict-broken\` pass covers every page.
delete site.markdown?.features?.linkValidation;

export default defineConfig(site);
`;
}

// --- step 4: seed goldens + committed previews, then git init+commit -------

function seedGoldensAndPreviews(def, outDir, resolvedDocs) {
  const generatedDest = path.join(outDir, resolvedDocs.generatedContent);
  copyTree(path.join(def.fixtureDir, def.goldenGeneratedContent), generatedDest);

  const preflightSrc = existsSync(path.join(def.fixtureDir, def.goldenPreflightExpected))
    ? path.join(def.fixtureDir, def.goldenPreflightExpected)
    : path.join(def.fixtureDir, def.goldenPreflightUpstream);
  const preflightDest = path.join(outDir, resolvedDocs.preflight);
  mkdirSync(path.dirname(preflightDest), { recursive: true });
  cpSync(preflightSrc, preflightDest);

  // Committed footprint SVG previews + their manifest (never regenerated by
  // this harness — that needs Docker/KiCad, out of #23's scope) and the
  // committed WRL model previews (regenerated fresh by the real `models`
  // command in step 6; seeding them first turns that into a byte-identical
  // "0 drift" proof instead of a first-write). `publicRoot` already carries
  // the host's own favicon files (step 3), so this is an additive merge, not
  // a replace.
  copyTree(path.join(def.fixtureDir, def.goldenPublic), path.join(outDir, resolvedDocs.publicRoot));
}

function gitInitCommit(outDir) {
  const gitEnv = {
    ...process.env,
    GIT_AUTHOR_NAME: "zudo-circuit-doc fixture harness",
    GIT_AUTHOR_EMAIL: "fixture-harness@zudo-circuit-doc.invalid",
    GIT_COMMITTER_NAME: "zudo-circuit-doc fixture harness",
    GIT_COMMITTER_EMAIL: "fixture-harness@zudo-circuit-doc.invalid",
  };
  assertRunOk("git init", run("git", ["init", "-q"], { cwd: outDir, env: gitEnv }));
  assertRunOk("git add", run("git", ["add", "-A"], { cwd: outDir, env: gitEnv }));
  assertRunOk(
    "git commit",
    run("git", ["commit", "-q", "-m", "fixture site: seed host scaffold + LED goldens"], {
      cwd: outDir,
      env: gitEnv,
    }),
  );
}

function gitDrift(outDir, relativePaths) {
  const result = execFileSync("git", ["status", "--porcelain", "--", ...relativePaths], {
    cwd: outDir,
    encoding: "utf8",
  });
  return result;
}

// --- step 5: obtain the runtime package, install, single-instance check ----

function requireRuntimeBuilt() {
  const indexJs = path.join(RUNTIME_PACKAGE_DIR, "lib/index.js");
  if (!existsSync(indexJs)) {
    throw new Error(`${path.relative(REPO_ROOT, indexJs)} is missing; run \`pnpm build\` first`);
  }
}

function packRuntime(packDestination) {
  requireRuntimeBuilt();
  mkdirSync(packDestination, { recursive: true });
  const result = runPnpm(
    ["--filter", RUNTIME_PACKAGE_NAME, "pack", "--pack-destination", packDestination],
    { cwd: REPO_ROOT },
  );
  assertRunOk("pnpm pack", result);
  // `pnpm pack` prints the absolute tarball path as its last non-empty stdout line.
  const lines = result.stdout.trim().split("\n").filter((line) => line.trim() !== "");
  const printedPath = lines[lines.length - 1]?.trim();
  if (printedPath !== undefined && existsSync(printedPath)) return printedPath;
  const tarballs = readdirSync(packDestination).filter((name) => name.endsWith(".tgz"));
  if (tarballs.length !== 1) {
    throw new Error(`expected exactly one tarball in ${packDestination}, found: ${tarballs.join(", ") || "none"}`);
  }
  return path.join(packDestination, tarballs[0]);
}

function findPrebuiltTarball(tarballsDir) {
  const candidates = readdirSync(tarballsDir).filter(
    (name) => name.endsWith(".tgz") && name.includes("zudo-circuit-doc"),
  );
  if (candidates.length !== 1) {
    throw new Error(
      `expected exactly one zudo-circuit-doc tarball in ${tarballsDir}, found: ${candidates.join(", ") || "none"}`,
    );
  }
  return path.join(tarballsDir, candidates[0]);
}

function packageRootFromResolved(resolvedFile, pkgName) {
  const marker = `${path.sep}node_modules${path.sep}${pkgName.split("/").join(path.sep)}${path.sep}`;
  const index = resolvedFile.lastIndexOf(marker);
  if (index === -1) {
    throw new Error(`could not locate ${pkgName}'s node_modules root in resolved path ${resolvedFile}`);
  }
  return resolvedFile.slice(0, index + marker.length);
}

/**
 * "a realpath check from the circuit package and the host resolves to the
 * same directory" (spec item 1.6): resolve `pkgName` as the `doc` host would
 * (it declares + imports it directly), and as `@takazudo/zudo-circuit-doc`
 * itself would from its own real install location (its peerDependency on
 * `pkgName` must be satisfied by that same location) — a `link:`-style escape
 * back into this monorepo's own node_modules would resolve the second one to
 * a different realpath.
 */
function assertSingleInstance(outDir, pkgName) {
  const req = createRequire(pathToFileURL(path.join(outDir, "doc/package.json")).href);
  const docDir = path.join(outDir, "doc");
  const fromDoc = req.resolve(pkgName, { paths: [docDir] });
  const circuitDocEntry = req.resolve(RUNTIME_PACKAGE_NAME, { paths: [docDir] });
  const circuitDocRealDir = path.dirname(realpathSync(circuitDocEntry));
  const fromCircuitDoc = req.resolve(pkgName, { paths: [circuitDocRealDir] });
  const a = realpathSync(packageRootFromResolved(fromDoc, pkgName));
  const b = realpathSync(packageRootFromResolved(fromCircuitDoc, pkgName));
  if (a !== b) {
    throw new Error(
      `multiple ${pkgName} instances resolved: doc host -> ${a}, ${RUNTIME_PACKAGE_NAME} -> ${b} ` +
        "(a link:-style escape back into the monorepo duplicates peer deps)",
    );
  }
  return a;
}

// --- main flow ---------------------------------------------------------------

export async function buildFixtureSite(options) {
  const {
    fixture,
    out = null,
    mode = "pack",
    tarballsDir = null,
    keep = false,
    log = () => {},
  } = options;
  const def = resolveFixture(fixture);
  if (def.key !== "led") {
    throw new Error(`fixture "${fixture}" is recognized but not implemented by this harness yet`);
  }
  if (mode !== "pack" && mode !== "file-dir") {
    throw new Error(`--mode must be "pack" or "file-dir" (got ${JSON.stringify(mode)})`);
  }

  const stepCheck = checkFixture({ fixtureDir: def.fixtureDir });
  if (!stepCheck.ok) {
    throw new Error(`fixtures/led lock check failed:\n${stepCheck.problems.map((p) => `  ${p}`).join("\n")}`);
  }
  if (stepCheck.materializedCount < stepCheck.materializedTotal) {
    throw new Error(
      `STEP is not materialized (${stepCheck.materializedCount}/${stepCheck.materializedTotal} files); ` +
        "run `pnpm fixtures:led:materialize` first",
    );
  }

  const outDir = out !== null ? path.resolve(out) : mkdtempSync(path.join(tmpdir(), `circuit-doc-${fixture}-site-`));
  if (existsSync(outDir) && readdirSync(outDir).length > 0) {
    throw new Error(`--out ${outDir} already exists and is not empty; remove it first`);
  }
  mkdirSync(outDir, { recursive: true });

  const scratch = mkdtempSync(path.join(tmpdir(), "circuit-doc-pack-"));
  const statusBefore = gitFixtureStatus();
  try {
    log(`building ${fixture} fixture site in ${outDir} (mode: ${mode})`);

    copyLedData(def, outDir);
    const resolvedConfig = await deriveConfig(def, outDir);
    copyHostFiles(outDir);

    let dependency;
    if (tarballsDir !== null) {
      dependency = dependencySpecFor({ mode, tarballPath: findPrebuiltTarball(tarballsDir), builtPackageDir: null });
    } else if (mode === "pack") {
      dependency = dependencySpecFor({ mode, tarballPath: packRuntime(scratch), builtPackageDir: null });
    } else {
      requireRuntimeBuilt();
      dependency = dependencySpecFor({ mode, tarballPath: null, builtPackageDir: RUNTIME_PACKAGE_DIR });
    }

    writeRootPackageJson(outDir, def, dependency);
    writeDocPackageJson(outDir, def, dependency);
    writePnpmWorkspaceYaml(outDir);
    writeText(path.join(outDir, "doc/zfb.config.ts"), buildZfbConfigSource(def.siteName));
    cpSync(path.join(REPO_ROOT, "examples/empty/.gitignore"), path.join(outDir, ".gitignore"));

    seedGoldensAndPreviews(def, outDir, resolvedConfig.docs);
    gitInitCommit(outDir);

    log("pnpm install (CI-like strictness)...");
    assertRunOk(
      "pnpm install",
      runPnpm(["install", "--config.strict-dep-builds=true"], { cwd: outDir }),
    );

    const preactRoot = assertSingleInstance(outDir, "preact");
    const zudoDocRoot = assertSingleInstance(outDir, "@takazudo/zudo-doc");
    log(`single preact instance: ${preactRoot}`);
    log(`single @takazudo/zudo-doc instance: ${zudoDocRoot}`);

    log("pnpm run build (models -> generate -> zfb build)...");
    const buildResult = runPnpm(["run", "build"], { cwd: outDir });
    assertRunOk("pnpm run build", buildResult);

    const generatedRel = path.relative(outDir, path.join(outDir, resolvedConfig.docs.generatedContent));
    const preflightRel = path.relative(outDir, path.join(outDir, resolvedConfig.docs.preflight));
    const modelsRel = path.join(path.relative(outDir, path.join(outDir, resolvedConfig.docs.publicRoot)), "assets/component-previews/models");
    const drift = gitDrift(outDir, [generatedRel, preflightRel, modelsRel]);
    if (drift !== "") {
      throw new Error(`generate/models produced drift against the seeded LED goldens:\n${drift}`);
    }
    log("zero generate/models drift against the seeded LED goldens");

    log("pnpm run check:site (check-built, scan, check-links --strict-anchors --strict-broken)...");
    const checkSiteResult = runPnpm(["run", "check:site"], { cwd: outDir });
    assertRunOk("pnpm run check:site", checkSiteResult);

    const statusAfter = gitFixtureStatus();
    if (statusAfter !== statusBefore) {
      throw new Error(`fixtures/led changed on disk while building the fixture site:\n${statusAfter}`);
    }

    return {
      outDir,
      kept: keep,
      buildOutput: buildResult.stdout,
      checkSiteOutput: checkSiteResult.stdout,
    };
  } finally {
    rmSync(scratch, { recursive: true, force: true });
    if (!keep) rmSync(outDir, { recursive: true, force: true });
  }
}
