/**
 * LED regression harness config (#21, M2 acceptance).
 *
 * Drives the packaged engine against the pinned `upstream/` corpus only.
 * Every path here is relative to this file's directory (`fixtures/led/`);
 * `root: "upstream"` puts every *project data* path inside the vendored tree,
 * while `circuit/*` fixture-local files (this harness's own publication
 * review artifacts) sit next to this config, outside `root`.
 *
 * `docs.generatedContent`/`docs.preflight`/`docs.publicRoot` point straight at
 * the committed `upstream/doc/...` locations, so `generate`/`check`/
 * `models --check`/`footprints check` compare against the real pinned goldens
 * — there is no separate `expected/doc/...` tree to keep in sync, except the
 * one deliberate exception recorded in `expected/` (see EXPECTED-CHANGES.md).
 */
import type { CircuitConfig } from "@takazudo/zudo-circuit-doc/config";

export default {
  configVersion: 1,
  root: "upstream",
  project: { name: "zudo-led-lamp", title: "zudo-led-lamp" },
  docs: {
    root: "upstream/doc",
    generatedContent: "upstream/doc/src/content/docs/components",
    preflight: "upstream/doc/component-docs/preflight.json",
    publicRoot: "upstream/doc/public",
    // Unused by this harness (check-led-fixture.mjs never runs a site build);
    // kept inside the copied fixture tree so it stays a contained path.
    dist: "upstream/doc/dist",
    agentResources: true,
    // The exact zudo-led-lamp marker (ADR-011): keeping it emits the legacy
    // frontmatter comment byte-for-byte and (see core/page.ts) turns the
    // generated-notice paragraph off automatically — there is no separate
    // config key for that.
    generatedMarker: "# GENERATED by doc/component-docs — do not edit; run `pnpm generate:components`",
    integrationGloss: "circuit/integration-gloss.json",
  },
  evidence: {
    contractVersion: 1,
    bundlesRoot: "upstream/.claude/skills",
    ownerPrefix: "component-",
    auditSkill: "component-spec-audit",
    integrationSkill: "circuit-spec-integration",
    inventory: "upstream/.claude/skills/component-spec-audit/references/inventory.json",
    integrationRules: "upstream/.claude/skills/circuit-spec-integration/references/rules.json",
    directRouting: "upstream/.claude/skills/component-spec-audit/fixtures/direct-routing.json",
    vendorQualifiers: "upstream/.claude/skills/component-spec-audit/references/external-vendor-qualifiers.json",
    forwardTests: "upstream/.claude/skills/circuit-spec-integration/references/forward-tests.json",
    // Only read by `--online`/`--refresh-source`, never by offline generate/check;
    // `upstream/tmp/` is already git-ignored (fixtures/led/.gitignore).
    sourceCache: "upstream/tmp/sources",
  },
  inventoryProvider: {
    kind: "led-generator-v1",
    specs: [
      { path: "upstream/scripts/schgen/board_p_spec.py" },
      { path: "upstream/scripts/schgen/board_l_spec.py" },
      { path: "upstream/scripts/schgen/swd_adapter_spec.py" },
    ],
  },
  publication: {
    selection: "circuit/selection.json",
    assets: "circuit/assets.json",
  },
  cad: {
    enabled: true,
    libraryName: "zudo-led-lamp",
    symbolLibraries: ["upstream/symbols/zudo-led-lamp.kicad_sym"],
    footprintMasterRoot: "upstream/footprints/kicad",
    footprintLibraryRoot: "upstream/footprints/kicad/zudo-led-lamp.pretty",
    modelRoot: "upstream/footprints/kicad/zudo-led-lamp.3dshapes",
    modelLocatorPrefix: "${KIPRJMOD}/../../footprints/kicad/zudo-led-lamp.3dshapes/",
    footprintPathBase: "upstream",
    previewRenderer: {
      image: "kicad/kicad@sha256:e638b79b0321f29395a5b783e94bb9f3c73303e8da15da27b8f5cb4b67a37729",
      version: "9.0.9",
      platform: "linux/amd64",
      layers: ["F.Cu", "F.Silkscreen", "F.Fabrication", "F.Courtyard"],
      theme: "KiCad Default",
      options: ["--black-and-white"],
    },
  },
  validation: {
    policy: "circuit/policy.json",
  },
} satisfies CircuitConfig;
