/**
 * LED regression harness config (#21, M2 acceptance).
 *
 * Drives the packaged engine against the pinned `upstream/` corpus only.
 * Every path here is relative to this file's directory (`fixtures/led/`);
 * `root: "upstream"` puts every *project data* path inside the vendored tree,
 * while `circuit/*` fixture-local files (this harness's own publication
 * review artifacts) sit next to this config, outside `root`.
 *
 * `docs.generatedContent`/`docs.preflight`/`docs.publicRoot` point straight at
 * the committed `upstream/doc/...` locations, so `generate`/`check`/
 * `models --check`/`footprints check` compare against the real pinned goldens
 * — there is no separate `expected/doc/...` tree to keep in sync, except the
 * one deliberate exception recorded in `expected/` (see EXPECTED-CHANGES.md).
 *
 * `scan`/`browserSmoke` below are never read by this file's own harness
 * (`scripts/check-led-fixture.mjs` builds no site); they exist so
 * `scripts/build-fixture-site.mjs` (#23) has a single source of truth to
 * import when it derives the fixture SITE's own config (docs.* rewritten to a
 * real zudo-doc host layout via `circuit/site-overlay.json`). Importing the
 * JSON files directly — rather than copying their values in by hand — is what
 * keeps `circuit/{scan-policy,browser-representatives}.json` the one place a
 * re-baseline or a representative-list change needs to happen.
 *
 * `circuit/scan-policy.json` re-baselines the real zudo-led-lamp site's scan
 * floors (100/60/100/150, expectedWithheld 6) for the fixture SITE, which has
 * none of that site's hand-authored project/architecture/research/decisions/
 * verification pages:
 *   - `minimumOwnedCanaries`/`minimumOwnedFiles` (100/60) are kept AS-IS: the
 *     OWNED tier scans only this feature's own output (generated MDX,
 *     preflight, built component pages, search/llms slices), which the
 *     surrounding host content never touches — measured 269 canaries x 81
 *     files on the fixture site, comfortably above the unchanged floor.
 *   - `minimumSiteCanaries`/`minimumSiteFiles` (266/185) and
 *     `expectedWithheld` (3) are measured fresh on the fixture site (2026-09,
 *     `pnpm build:led-site`): the SITE tier subtracts canaries any OTHER
 *     authored page already publishes, and this host authors far fewer pages
 *     than the real site (no project/architecture/research/decisions/
 *     verification sections), so both the withheld count and the site-wide
 *     file/canary totals are genuinely different numbers here, not the real
 *     site's 150/6.
 */
import type { CircuitConfig } from "@takazudo/zudo-circuit-doc/config";
import browserSmoke from "./circuit/browser-representatives.json" with { type: "json" };
import scan from "./circuit/scan-policy.json" with { type: "json" };

export default {
  configVersion: 1,
  root: "upstream",
  project: { name: "zudo-led-lamp", title: "zudo-led-lamp" },
  docs: {
    root: "upstream/doc",
    generatedContent: "upstream/doc/src/content/docs/components",
    preflight: "upstream/doc/component-docs/preflight.json",
    publicRoot: "upstream/doc/public",
    // Unused by this harness (check-led-fixture.mjs never runs a site build);
    // kept inside the copied fixture tree so it stays a contained path.
    dist: "upstream/doc/dist",
    agentResources: true,
    // The exact zudo-led-lamp marker (ADR-011): keeping it emits the legacy
    // frontmatter comment byte-for-byte.
    generatedMarker: "# GENERATED by doc/component-docs — do not edit; run `pnpm generate:components`",
    // Explicit: this reproduces pre-extraction output byte-for-byte, which
    // never carried the ADR-020 generated-notice paragraph. Set here rather
    // than relying on the legacy-marker inference (#36).
    generatedNotice: false,
    integrationGloss: "circuit/integration-gloss.json",
  },
  evidence: {
    contractVersion: 1,
    bundlesRoot: "upstream/.claude/skills",
    ownerPrefix: "component-",
    auditSkill: "component-spec-audit",
    integrationSkill: "circuit-spec-integration",
    inventory: "upstream/.claude/skills/component-spec-audit/references/inventory.json",
    integrationRules: "upstream/.claude/skills/circuit-spec-integration/references/rules.json",
    directRouting: "upstream/.claude/skills/component-spec-audit/fixtures/direct-routing.json",
    vendorQualifiers: "upstream/.claude/skills/component-spec-audit/references/external-vendor-qualifiers.json",
    forwardTests: "upstream/.claude/skills/circuit-spec-integration/references/forward-tests.json",
    // Only read by `--online`/`--refresh-source`, never by offline generate/check;
    // `upstream/tmp/` is already git-ignored (fixtures/led/.gitignore).
    sourceCache: "upstream/tmp/sources",
  },
  inventoryProvider: {
    kind: "led-generator-v1",
    specs: [
      { path: "upstream/scripts/schgen/board_p_spec.py" },
      { path: "upstream/scripts/schgen/board_l_spec.py" },
      { path: "upstream/scripts/schgen/swd_adapter_spec.py" },
    ],
  },
  publication: {
    selection: "circuit/selection.json",
    assets: "circuit/assets.json",
  },
  cad: {
    enabled: true,
    libraryName: "zudo-led-lamp",
    symbolLibraries: ["upstream/symbols/zudo-led-lamp.kicad_sym"],
    footprintMasterRoot: "upstream/footprints/kicad",
    footprintLibraryRoot: "upstream/footprints/kicad/zudo-led-lamp.pretty",
    modelRoot: "upstream/footprints/kicad/zudo-led-lamp.3dshapes",
    modelLocatorPrefix: "${KIPRJMOD}/../../footprints/kicad/zudo-led-lamp.3dshapes/",
    footprintPathBase: "upstream",
    previewRenderer: {
      image: "kicad/kicad@sha256:e638b79b0321f29395a5b783e94bb9f3c73303e8da15da27b8f5cb4b67a37729",
      version: "9.0.9",
      platform: "linux/amd64",
      layers: ["F.Cu", "F.Silkscreen", "F.Fabrication", "F.Courtyard"],
      theme: "KiCad Default",
      options: ["--black-and-white"],
    },
  },
  validation: {
    policy: "circuit/policy.json",
  },
  scan,
  browserSmoke,
} satisfies CircuitConfig;
